name: Release

on:
  push:
    tags: [v*]
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
          cache: true

      - name: Test
        run: go test ./...

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: make clean && make && make sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.zip
            build/*.zip.sha256
